### ISSUE TITLE
Error when using with next.js 

### ISSUE THREAD

**Issue by skopz356** [beekai-oss/little-state-machine#138]
First of all thank you for creating this library. 
I tried to use this library with next.js a when I enter some data into the state and reload the page. I get error saying `Error: Text content does not match server-rendered HTML.`. I know that I can make the component only client side, but I do not want to. Is there any other option? 

Reproduction:
1. Visit https://codesandbox.io/s/nextjs-react-hook-form-wizard-form-forked-otzv44?file=/pages/index.js
2. Enter some data into 'First Name', then reload by reload icon in sandbox.

**Comment by bluebill1049** [comment]
thanks for the issue report currently this library is limited to clients only and kept simple and small (<1kb).
