### ISSUE TITLE
how to get the global state value  outside of the component.

### ISSUE THREAD

**Issue by NarenderSiri** [beekai-oss/little-state-machine#141]
const log = (store) => {
     return store;
  };
 
  createStore({
    yourDetail: { tenantId: "" },
    
  },{
    middleWares: [ log ],
  }
  );

export const Getstatevalue = {  
// i want to export the  state value  from here out side the component 
 }

const App=() => {
//It is working here 
   const { actions, state,getState  } = useStateMachine({ updateName });
}

**Comment by bluebill1049** [comment]
no supported at moment, we can consider that later on.
