### ISSUE TITLE
Access the CreateStore Outside a React Component

### ISSUE THREAD

**Issue by NarenderSiri** [beekai-oss/little-state-machine#143]
Store value I want to use here ..
This is too important to me . Please give answer

export default function setupAxios(axios, store) {
axios.interceptors.request.use(
(config) => {
const {
auth: { tokens: { authorization_token } },
} = store.getState();

        if (authorization_token) {
            config.headers.Authorization = `Bearer ${authorization_token}`;
        }

        return config;
    },
   (err) => Promise.reject(err)
);
}

**Comment by NarenderSiri** [comment]
Store value I want to use here ..
This is too important to me . Please give answer


export default function setupAxios(axios, store) {
    axios.interceptors.request.use(
        (config) => {
            const {
                auth: { tokens: { authorization_token } },
            } = store.getState();

            if (authorization_token) {
                config.headers.Authorization = `Bearer ${authorization_token}`;
            }

            return config;
        },
       (err) => Promise.reject(err)
    );
}

**Comment by bluebill1049** [comment]
if you are using session storage, you can just query the session storage data.
